# Generated by Django 3.2.14 on 2022-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='titles',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='words',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
